
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nwd.BackOffice.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Album
{

    public Album()
    {

        this.Tracks = new HashSet<Track>();

    }


    public int Id { get; set; }

    public string Title { get; set; }

    public System.TimeSpan Duration { get; set; }

    public System.DateTime ReleaseDate { get; set; }

    public string Type { get; set; }

    public string CoverImagePath { get; set; }

    public Nullable<int> Artist_Id { get; set; }



    public virtual Artist Artist { get; set; }

    public virtual ICollection<Track> Tracks { get; set; }

}

}
