
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nwd.BackOffice.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Song
{

    public Song()
    {

        this.Artists = new HashSet<Artist>();

        this.Tracks = new HashSet<Track>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> Composed { get; set; }



    public virtual ICollection<Artist> Artists { get; set; }

    public virtual ICollection<Track> Tracks { get; set; }

}

}
