
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nwd.BackOffice.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Track
{

    public int AlbumId { get; set; }

    public int Number { get; set; }

    public System.TimeSpan Duration { get; set; }

    public string FileRelativePath { get; set; }

    public Nullable<int> Song_Id { get; set; }



    public virtual Album Album { get; set; }

    public virtual Song Song { get; set; }

}

}
